### ISSUE TITLE
How it differs from python-telegram-bot?

### ISSUE THREAD

**Issue by SmartManoj** [SilverOS/Silbot-Py#3]
https://pypi.org/project/python-telegram-bot/

**Comment by SilverOS** [comment]
I can't really say because I never used it, but they look very different in everything excluding variables

**Comment by SmartManoj** [comment]
https://github.com/SilverOS/Silbot-Py/blob/679a229c6b6f8cc9f2147934f4a2fe8092bc5de0/examples/echobot.py#L22

It should be snake_case as per PEP8.

**Comment by SilverOS** [comment]
In this framework, similarity to botAPI has the priority on PEP8
